#!/bin/bash

## Description: Build the project by running composer install, drush site-install and few other commands.
## Usage: install
## Example: "ddev install"
YELLOW='\033[1;33m'
GREEN='\033[1;32m'
BLUE='\033[1;34m'
RESET_COLOR='\033[0m'

printf "Working in: ${YELLOW}${WEBSERVER_DOCROOT}${RESET_COLOR}\nRunning: ${YELLOW}composer install${RESET_COLOR}\n";
printf "Composer: ${BLUE}`composer --version`${RESET_COLOR}\n";

composer install --working-dir $WEBSERVER_DOCROOT && \
  drush si --account-pass=admin tinyurlprofile -y && \
  printf "${GREEN}All done!${RESET_COLOR}\n";


